version: '3'

services:
  home-assistant:
    image: homeassistant/home-assistant
    volumes:
      - ./config:/config
    devices:
      - /dev/zwave:/dev/zwave
    ports:
      - 8123:8123
      - 8989:8989
    logging:
      options:
        max-size: "1m"
        max-file: "10"
    depends_on:
      - influx

  influx:
    image: influxdb:1.3-alpine
    volumes:
      - influxdb:/var/lib/influxdb
      - ./initdb.d:/docker-entrypoint-initdb.d:ro

  grafana:
    image: grafana/grafana:4.5.2
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - influx
    environment:
      - "GF_SECURITY_DATA_SOURCE_PROXY_WHITELIST=influx:8086"
      - "GF_AUTH_DISABLE_LOGIN_FORM=true"
      - "GF_AUTH_GOOGLE_ENABLED=true"
      - "GF_AUTH_GOOGLE_SIGN_UP=false"
      - "GF_USERS_ALLOW_SIGN_UP=false"
      - "GF_AUTH_BASIC=false"

volumes:
  influxdb:
  grafana-storage:
