- id: auto_upstairs_on_with_motion
  alias: auto upstairs on with motion
  trigger:
  - entity_id: binary_sensor.motion_stairs
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.motion_upstairs
    from: 'off'
    platform: state
    to: 'on'
  action:
  - service: timer.cancel
    data:
      entity_id: timer.upstairs_light_timer
  - condition: and
    conditions:
    - condition: numeric_state
      below: '40'
      entity_id: sensor.estimated_outdoor_brightness
  - service: light.turn_on
    data:
      entity_id: light.upstairs_hub_lights
- id: begin_upstairs_off_timer
  alias: begin upstairs off timer
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_upstairs
    from: 'on'
    to: 'off'
  action:
  - service: timer.start
    data:
      entity_id: timer.upstairs_light_timer
- id: auto_upstairs_off_after_timer
  alias: auto upstairs off after timer
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.upstairs_light_timer
  action:
  - service: light.turn_off
    data:
      entity_id: light.upstairs_hub_lights
- id: auto_downstairs_on_with_motion
  alias: auto downstairs on with motion
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_stairs
    from: 'off'
    to: 'on'
  action:
  - service: timer.cancel
    data:
      entity_id: timer.downstairs_light_timer
  - condition: and
    conditions:
    - condition: numeric_state
      entity_id: sensor.estimated_outdoor_brightness
      below: '40'
    - condition: state
      entity_id: light.upstairs_hub_lights
      state: 'on'
  - service: light.turn_on
    data:
      entity_id: light.downstairs_hub_lights
- id: begin_downstairs_off_timer
  alias: begin downstairs off timer
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_stairs
    from: 'on'
    to: 'off'
  action:
  - service: timer.start
    data:
      entity_id: timer.downstairs_light_timer
- id: auto_downstairs_off_after_timer
  alias: auto downstairs off after timer
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.downstairs_light_timer
  action:
  - service: light.turn_off
    data:
      entity_id: light.downstairs_hub_lights
- action:
  - data: {}
    service: script.shutdown
  alias: auto shutdown when away
  id: '1501406443734'
  trigger:
  - entity_id: binary_sensor.presence
    from: 'on'
    platform: state
    to: 'off'
    for:
      minutes: 5
- action:
  - data: {}
    service: script.startup
  alias: auto startup when home
  id: '1501968460139'
  trigger:
  - entity_id: binary_sensor.presence
    from: 'off'
    platform: state
    to: 'on'
- id: enable_modem_reboot_loop
  alias: enable modem reboot loop
  trigger:
  - platform: state
    entity_id: binary_sensor.modem_alive
    from: 'on'
    to: 'off'
  action:
  - service: timer.start
    data:
      entity_id: timer.modem_reboot_loop
      duration: 120
- id: disable_modem_reboot_loop
  alias: disable modem reboot loop
  trigger:
  - platform: state
    entity_id: binary_sensor.modem_alive
    from: 'off'
    to: 'on'
  action:
  - service: timer.cancel
    data:
      entity_id: timer.modem_reboot_loop
- id: modem_reboot_loop
  alias: modem reboot loop
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.modem_reboot_loop
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.modem
  - delay: 5
  - service: switch.turn_on
    data:
      entity_id: switch.modem
  - condition: and
    conditions:
    - condition: state
      entity_id: binary_sensor.modem_alive
      state: 'off'
  - service: timer.start
    data:
      entity_id: timer.modem_reboot_loop
      duration: 600
- action:
  - data:
      entity_id: group.office_lights
    service: homeassistant.turn_on
  alias: auto office lights on after dark
  condition:
  - condition: state
    entity_id: switch.bowser
    state: 'on'
  - condition: state
    entity_id: binary_sensor.presence
    state: 'on'
  id: '1503261964656'
  trigger:
  - below: '30'
    entity_id: sensor.estimated_outdoor_brightness
    platform: numeric_state
- action:
  - data:
      message: You left something open.
      title: House open
    service: notify.push
  alias: notify on left open
  id: '1503273486895'
  trigger:
  - platform: template
    value_template: '{{ is_state("cover.garage_door_opener", "open") and not is_state("device_tracker.pixel_sailfish",
      "home") }}'
- action:
  - data_template:
      message: Home Assistant {{ states.updater.updater.state }} is now available.
      title: New Home Assistant Release
      data:
        disable_notification: true
    service: notify.telegram
  alias: notify on new home assistant release
  id: '1503275062301'
  trigger:
  - entity_id: updater.updater
    platform: state
- action:
  - data:
      brightness: 255
      entity_id: light.bedroom_lights
      kelvin: 2000
      transition: 1800
    service: light.turn_on
  alias: wake up for work
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  - condition: template
    value_template: '{{ states.calendar.work_holiday.state == "off" or states.calendar.work_holiday.attributes.all_day
      == false }}'
  - condition: template
    value_template: '{{ states.calendar.work_vacation.state == "off" or states.calendar.work_vacation.attributes.all_day
      == false }}'
  id: '1503862324643'
  trigger:
  - at: '7:00'
    platform: time
- action:
  - data:
      entity_id: climate.downstairs
      fan_mode: 'on'
    service: climate.set_fan_mode
  - delay: 900
  - data:
      entity_id: climate.downstairs
      fan_mode: auto
    service: climate.set_fan_mode
  alias: periodic fan downstairs
  condition:
  - condition: state
    entity_id: binary_sensor.presence
    state: 'on'
  id: '1503863375784'
  trigger:
  - entity_id: binary_sensor.presence
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.downstairs_thermostat_fan
    platform: state
    to: 'off'
    for:
      minutes: 45
  - event: start
    platform: homeassistant
- action:
  - data:
      entity_id: climate.upstairs
      fan_mode: 'on'
    service: climate.set_fan_mode
  - delay: 900
  - data:
      entity_id: climate.upstairs
      fan_mode: auto
    service: climate.set_fan_mode
  alias: periodic fan upstairs
  condition:
  - condition: state
    entity_id: binary_sensor.presence
    state: 'on'
  id: '1503863375785'
  trigger:
  - entity_id: binary_sensor.presence
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.upstairs_thermostat_fan
    platform: state
    to: 'off'
    for:
      minutes: 45
  - event: start
    platform: homeassistant
- id: 'christmas_on'
  alias: Christmas On
  trigger:
  - platform: numeric_state
    entity_id: sensor.estimated_outdoor_brightness
    below: '50'
  - platform: time
    at: '5:00'
  condition:
  - condition: numeric_state
    below: '50'
    entity_id: sensor.estimated_outdoor_brightness
  - condition: time
    after: '5:00'
    before: '23:00'
  action:
  - service: homeassistant.turn_on
    data:
      entity_id: group.christmas_lights
- id: 'christmas_off'
  alias: Christmas Off
  trigger:
  - platform: numeric_state
    entity_id: sensor.estimated_outdoor_brightness
    above: '50'
  - platform: time
    at: '23:00'
  condition:
  - condition: or
    conditions:
    - condition: numeric_state
      above: '50'
      entity_id: sensor.estimated_outdoor_brightness
    - condition: time
      after: '23:00'
  action:
  - service: homeassistant.turn_on
    data:
      entity_id: group.christmas_lights
