cover.myq:
  hidden: true
cover.garage_door_opener:
  device_class: garage
  friendly_name: Garage Door
switch.modem:
  assumed_state: true
light.bedroom:
  hidden: true
light.office_hue:
  hidden: false
group.calendar:
  friendly_name: Calendar
  hidden: false
group.christmas_lights:
  icon: mdi:pine-tree
switch.tpmini1:
  friendly_name: Porch Christmas Lights
switch.wemo_switch_5ea:
  assumed_state: true
  friendly_name: Window Christmas Lights
cover.shade_bedroom_east_level:
  friendly_name: Bedroom East
cover.shade_bedroom_west_level:
  friendly_name: Bedroom West
cover.shade_living_room_level:
  friendly_name: Living Room
cover.shade_office_east_level:
  friendly_name: Office East
cover.shade_office_west_level:
  friendly_name: Office West
