cover.myq:
  hidden: true
cover.garage_door_opener:
  device_class: garage
  friendly_name: garage door
switch.modem:
  assumed_state: true
light.bedroom:
  hidden: true
light.office_hue:
  hidden: true
