---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: postgres
  namespace: home
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~12.1
spec:
  releaseName: home-postgres
  chart:
    repository: https://charts.bitnami.com/
    name: postgresql
    version: "7.1.0"
  values:
    image:
      repository: bitnami/postgresql
      tag: "12.1.0"
    postgresqlUsername: home_assistant
    postgresqlDatabase: home_assistant
    persistence:
      enabled: true
      existingClaim: postgres
  valueFileSecrets:
    - name: postgres-secret
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  namespace: home
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: home
spec:
  encryptedData:
    values.yaml: AgAxKTpi5LKUaW5CX0/qug3J9X2WelGsXlkf+JuZdA+EckvDhXOY9e41aHf4aJBCqx+t+a+OtykPTH1am0nf+T02N2jZntvORcKJsiTQAQgKkOqlbfitTgEHV90SBmX1ZGwokHEz2jxJ5V34SEo/3noE5qFCrjs8W+rxSjzLRooI4AuzGAmOxgH3kfoTB/UEREkXkhDJgG3wiJyHw2sV9Ld5WzKi6KcLxSLJtlgflXVMGbwou+grYSlFzQ/SPOkTUm2XEDdbP/HylOevTngT1NUWlvwOQGuLjrsjAniULes2CePFrg1tvkZSuoRI65cyUWyHlGmgJhFp4lvdQGwlz7h0Q0+IR0IQiQDB2jGYcqGDYw69vUq7djcKdgUG4ePcdaNVQoL4M9qC1AxsOcmpXY+lUiwpYyNCeQZnexVB3fNN/p5myo1W9rWTnzYUkFWVcWRHqeDdPZ8OlS865OrpvFDWVhkHAyzIoQ/Jsevi18YCojuFF1LXVB0T47VFkeNWIRvi8hrpgifebuk1XksImhKT15OcPDwPJVgi4PRZKtKcZQAl31hd3kAZd8HKWw59Q00TVADSst+Bw90f+gpYFt7DcpKKsnf1+Y0VwSmnYm31BeGX+GuXQ+MujW3Lfiyw1AqKvC8K3noTr/Hu3dQn0xiwIaPgad67Ha6pPSRut97jF830POXp/p5jIUP8eJQx1YvMaj3jq9VA/HoK3z5NB+y4ZwgO/nNGU50vKpSKvteFYGrbJvQQ7UPsBB5SKjmRkTddLVfq
