---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: vernemq
  namespace: home
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: glob:1.9.*-alpine
spec:
  releaseName: vernemq
  chart:
    repository: https://vernemq.github.io/docker-vernemq/
    name: vernemq
    version: "1.4.4"
  values:
    image:
      repository: erlio/docker-vernemq
      tag: 1.9.2-1-alpine
    service:
      mqtt:
        enabled: true
  valuesFrom:
    - secretKeyRef:
        name: verne-users
        key: users.yaml
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: verne-users
  namespace: home
spec:
  encryptedData:
    users.yaml: AgCDTXo/hFdz30zz5upIuHJHPmgCxVSPP1xTtrpopMc7ykYJ0DQCEMtp0rjxiHPpk5vcG/TK3sfzMPc5EEV4s+eGFNMz0ZvssfCfjwiGlCEWXiA2MgAbb353zE1JcKbRVxLqaXOytiobsWg0V2tumub7jJGAalXH4NtS92zNscwK/6JqnCMcSZXHR/QDQ5xgyxmS6um9OgdPt3cH38yJrZ6LqGVpnRtuFnI3ZLds4pOjZqjDDfN/zVzFWfAWUCLmAidV6A0PwUMPxcyosn0SipCEn5rncTKoCixBmgp6LN+DxCsTbeFFX2SK7NPnraFwhLhpR1LJ/RPbncs+6LSxIKrYFBqXWDbPgZK+Bf5WuIBzLD6yuDH183G7bq5CgZlGdz1senf8VG9M6waMY9u8KlI1oJUZ/1JeoqzK2uRF3EQAwE7FneBGRk5mVe62sb8NZ5bwLeUuajMETqdJqb/3rqmBRwKwkfIy+/ExyT3Imrbd7QfZVKTl/S+uLObhxj6uzlNE0nAdk7qod5GbvOI5iUg4ZAPYUE1vr30T1pag/d0+5v0HNTbdv0qHb+LidHuPWGteZ0kUVroM1M7/NDuUt4i0FXf+g4SxK2ufWxwX+zY2Xlv0Xk1ZybZrkoDHJztdG86b/xLFfPLFHFW8aG6y0ooNhLlHSZOSLWF5Fc0m2rrwjXS6F/YaMOp5Uij9jV42NjWV8+UDJHrpgK0c1pkaXn5VNG5ZnsdPlqoP5kajbx0tHNvHaBEVx4r99N3Ey+vclpO3jdIYZrdmWLHYNy1kORoW/4OIwRGoyUAm9WbzgfY8tGGZaPqam0fsGjqqpTgCFLJRu//2Y3fgIkszjZqEDq7/nllyUsc9CGxLWVsj1LCKpSX09uobEa/HtGdx9QXiVlO2aELlrnsP1BmVnK+bPA6ORI8L6zpzr/xVEghumqDDG0u5gxdy0KpuROurlXH+Xohn+AU/XNvUcMipTxVnonsL5g+oCuNqXVFQvOAZGvU1mGg3kzO0cgjrYqdWBOdP/wT4KE1BiK3QsB5FbVfIpqkSDsXn6+NKlOahigQEOJgIwMDPIrCwcXPnn7LE+yZKUu7OMeqS2bAXCH8BWIshAYajkiWd6fY3DWTGlsAI0sYF90aq4YamNBR4WSsipzanB7Soxxcci3ke3X5YsdMFmLdppaQwztxRLEYt3xLJKTYfQzZ2KdRUHGjr0QHtQsS92BREOF+A
---
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  namespace: home
  name: vernemq
  labels:
    app.kubernetes.io/instance: vernemq
    app.kubernetes.io/name: vernemq
  annotations:
    kubernetes.io/ingress.class: voyager
    ingress.appscode.com/type: HostPort
spec:
  rules:
    - host: home.okayserver.gq
      tcp:
        port: "8883"
        backend:
          serviceName: vernemq
          servicePort: "1883"
  tls:
    - hosts:
        - home.okayserver.gq
      secretName: home-assistant-tls
