---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~v0.11.0
    fluxcd.io/tag.webhook: semver:~v0.11.0
    fluxcd.io/tag.cainjector: semver:~v0.11.0
spec:
  releaseName: cert-manager
  chart:
    repository: https://charts.jetstack.io/
    name: cert-manager
    version: v0.11.0
  values:
    image:
      repository: quay.io/jetstack/cert-manager-controller
      tag: v0.11.1
    webhook:
      image:
        repository: quay.io/jetstack/cert-manager-webhook
        tag: v0.11.0
    cainjector:
      image:
        repository: quay.io/jetstack/cert-manager-cainjector
        tag: v0.11.0
    ingressShim:
      defaultIssuerName: letsencrypt-prod
      defaultIssuerKind: ClusterIssuer
