---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: dummy-site
  namespace: system
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~1.15
spec:
  releaseName: dummy-site
  chart:
    git: ssh://git@github.com/mdonoughe/home
    ref: master
    path: charts/dummy-site
  values:
    image:
      repository: nginx
      tag: 1.15.9
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: 'true'
      hosts:
        - okayserver.gq
      tls:
        - hosts:
          - okayserver.gq
          secretName: dummy-site-tls
    nodeSelector:
      kubernetes.io/hostname: okayserver.gq
