---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: voyager
  namespace: system
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.voyager: semver:~v11.0
    fluxcd.io/tag.haproxy: glob:1.9.6-v11.0.*-alpine
spec:
  releaseName: voyager
  chart:
    repository: https://charts.appscode.com/stable/
    name: voyager
    version: v11.0.1
  values:
    voyager:
      tag: v11.0.1
    haproxy:
      tag: 1.9.6-v11.0.1-alpine
    cloudProvider: baremetal
    ingressClass: voyager
