FROM homeassistant/home-assistant:0.56.2

COPY lutron_caseta.py homeassistant/components/lutron_caseta.py
COPY pylutron-caseta/pylutron_caseta/__init__.py pylutron-caseta/pylutron_caseta/leap.py pylutron-caseta/pylutron_caseta/smartbridge.py /usr/local/lib/python3.6/site-packages/pylutron_caseta/
